kind: pipeline
workspace:
  base: /drone/src
  path: eureka-server
pipeline:
  build:
    image: 'maven:3.5.2-jdk-8'
    privileged: true
    commands:
      - 'mvn clean package'
    volumes:
      - '/drone/maven-repo:/root/.m2'
  public-dev:
    image: plugins/docker
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    commands:
      - 'docker login --username=潘金天1992 --password=panjintian1992 registry.cn-beijing.aliyuncs.com'
      - 'docker build --rm  -t demo .'
      - 'docker tag demo registry.cn-beijing.aliyuncs.com/frode/banana:master'
      - 'docker push registry.cn-beijing.aliyuncs.com/frode/banana:master'
    when:
      branch: master
      event: push
  rancher-online:
    image: peloton/drone-rancher
    url: 'http://182.92.189.28:8080'
    access_key: 9DC5B73C654423356E28
    secret_key: 1ZR2QFbNq38zQK9aVNSEwQGsAXEHL2RrMueMt2GN
    service: demo/demo
    docker_image: registry-vpc.cn-beijing.aliyuncs.com/frode/banana:master
    start_first: false
    confirm: true
    timeout: 180
    when:
      branch: master
      event: push